############
#Deployment#
############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-project
  labels:
    app: camel-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-project
  template:
    metadata:
      labels:
        app: camel-project
    spec:
      containers:
        - name: camel-project
          image: andrewmereuta/camel-project # should be my image which I upload there: andrewmereuta/camel-project
          ports:
            - containerPort: 9000
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: url
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: secret-keys
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: secret-keys
                  key: password
---
#########
#Service#
#########
apiVersion: v1
kind: Service
metadata:
  name: camel-project-service
spec:
  selector:
    app: camel-project
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
