############
#Deployment#
############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-project
  labels:
    app: camel-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-project
  template:
    metadata:
      labels:
        app: camel-project
    spec:
      containers:
      - name: camel-project
        image: andrewmereuta/camel-project # should be my image which I upload there: andrewmereuta/camel-project
        ports:
        - containerPort: 9000
        env:
        - name: spring.datasource.url
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: url
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: secret-keys
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: secret-keys
              key: password
---
#########
#Service#
#########
apiVersion: v1
kind: Service
metadata:
  name: camel-project-service
  annotations:
    konghq.com/plugins: camel-api-jwt, rate-limit, sample-plugin
spec:
  selector:
    app: camel-project
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
#########
#Ingress#
#########
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camel-api
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: camel-api.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: camel-project-service
            port:
              number: 9000

# kubectl create secret generic kong-session-config --from-file=admin_gui_session_conf --from-file=portal_session_conf
# kubectl create secret generic kong-enterprise-license --from-file=license=./license.json
# kubectl create secret generic kong-enterprise-superuser-password --from-literal=password=pass
# helm install kong-ee kong/kong --values=kong-enterprise-full-k4k8s.yml
# kubectl port-forward deploy/kong-ee-kong 8001:8001
#
# kubectl apply -f ./secretMap.yaml
# kubectl apply -f ./jwt-plugin.yaml
# kubectl apply -f ./config-map.yaml
# kubectl apply -f ./persistent-volume.yaml
# sleep(40)
# kubectl apply -f ./camel-deploy.yaml
# kubectl apply -f ./jwt-consumer.yaml
#
# kubectl delete -f ./secretMap.yaml
# kubectl delete -f ./config-map.yaml
# kubectl delete -f ./persistent-volume.yaml
# kubectl delete -f ./camel-deploy.yaml
# helm delete kong-ee
# For safeness I recommend to reset Kuber Cluster


#######################
# Kong with CRDs
# 1) Stop all previous processes(only camel processes)
# 2) Create Secret
# 3) Create Plugin
# 4) Create Map
# 5) Create Persistent Volume
# 6) Create Deployment
# 7) Create Consumer