#########
#Plugins#
#########
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: camel-api-jwt
plugin: jwt
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit
config:
  minute: 5
  limit_by: ip
  policy: local
plugin: rate-limiting