#########
#Secrets#
#########
apiVersion: v1
kind: Secret
metadata:
  name: secret-keys
type: Opaque
data:
  username: cm9vdA== # base64 encoded username 'root'
  password: cGFzc3dvcmQ= # base64 encoded password 'password'
---
apiVersion: v1 # This part is only used with
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  kongCredType: jwt
  key: apikey
  algorithm: HS256
  secret: secret

# 2

