#########
#Plugins#
#########
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: sample-plugin
config:
  requestHeader: "x-my-custom-request-header"
  responseHeader: "This is my sample response header"
plugin: sample-plugin